version: "3.6"

services:
  maria:
    image: mariadb:10.7.1-focal
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_DATABASE=${MYSQL_SCHEMA}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - "MONGO_INITDB_DATABASE=${MYSQL_SCHEMA}"
      - "MONGO_INITDB_ROOT_USERNAME=${MYSQL_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MYSQL_PASSWORD}"

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    ports:
      - "${MEILISEARCH_PORT:-7700}:${MEILISEARCH_PORT:-7700}"
    environment:
      - "MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY}"
